name = "high-flybet-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=high-flybet.es"
HMAC_KEY = "f9e4b9997aa23be02a2ec00dbfd7d75965ce847473d30c8e4f00d2274414f5ff"
COOKIE_NAME = "ki7"
PLAY_PATH = "play-now"
BUTTON_ID = "pcfbb85b5396d68deb129fe112623a9ed"
GATE_SALT = "b6ae72b33b626356"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "xarm"
CTA_SELECTOR = ".play-button"
